name: dito_sdk
description: A Flutter package by Dito that enables user registration and user event tracking.
version: 0.5.7
homepage: https://github.com/ditointernet/sdk_mobile_flutter

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.6.0
  crypto: 3.0.7
  device_info_plus: 12.3.0
  package_info_plus: 9.0.0
  sqflite: 2.4.2
  firebase_messaging: 16.1.1
  flutter_local_notifications: 20.0.0
  firebase_core: 4.4.0
  sqflite_common_ffi: 2.4.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0"
